# Generated by Django 4.2.9 on 2024-02-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriechart',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7),
        ),
        migrations.AddField(
            model_name='caloriechart',
            name='description',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='caloriechart',
            name='is_cal_per_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caloriechart',
            name='is_cal_per_kg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caloriechart',
            name='is_cal_per_liter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caloriechart',
            name='item_name',
            field=models.CharField(default='street', max_length=120),
        ),
    ]
