# Generated by Django 4.2.9 on 2024-02-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0002_caloriechart_calories_caloriechart_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriechart',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='caloriechart',
            name='item_name',
            field=models.CharField(max_length=120),
        ),
    ]
